#!/bin/bash
shopt -s nullglob

echo "Hello" >&2

/usr/share/white/white_loader -l /usr/share/white/nullfs_prelink.dylib

for i in Applications Developer Library System User bin boot cores lib mnt sbin usr; do
    mount -t null -o union /private/var/null/$i /$i &
done
wait

dylibs=$(for dylib in /Library/LaunchExtensions/*.dylib; do echo -n "$dylib:"; done)
export DYLD_INSERT_LIBRARIES=${dylibs%:}
exec -a /sbin/launchd /sbin/launchd.real

